
package com.affiliatewindow.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-06-18T17:32:54.972-07:00
 * Generated source version: 2.4.2
 * 
 */
public final class ApiPortType_ApiPort_Client {

    private static final QName SERVICE_NAME = new QName("http://api.affiliatewindow.com/", "ApiService");

    private ApiPortType_ApiPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ApiService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ApiService ss = new ApiService(wsdlURL, SERVICE_NAME);
        ApiPortType port = ss.getApiPort();  
        
        {
        System.out.println("Invoking getCommissionGroupList...");
        int _getCommissionGroupList_iMerchantId = 0;
        try {
            java.util.List<com.affiliatewindow.api.CommissionGroup> _getCommissionGroupList__return = port.getCommissionGroupList(_getCommissionGroupList_iMerchantId);
            System.out.println("getCommissionGroupList.result=" + _getCommissionGroupList__return);

        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMerchantList...");
        com.affiliatewindow.api.Relationship _getMerchantList_sRelationship = null;
        try {
            java.util.List<com.affiliatewindow.api.Merchant> _getMerchantList__return = port.getMerchantList(_getMerchantList_sRelationship);
            System.out.println("getMerchantList.result=" + _getMerchantList__return);

        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMerchant...");
        java.util.List<java.lang.Integer> _getMerchant_aMerchantIds = null;
        try {
            java.util.List<com.affiliatewindow.api.Merchant> _getMerchant__return = port.getMerchant(_getMerchant_aMerchantIds);
            System.out.println("getMerchant.result=" + _getMerchant__return);

        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCommissionGroup...");
        int _getCommissionGroup_iMerchantId = 0;
        java.lang.String _getCommissionGroup_sCommissionGroupCode = "";
        try {
            com.affiliatewindow.api.CommissionGroup _getCommissionGroup__return = port.getCommissionGroup(_getCommissionGroup_iMerchantId, _getCommissionGroup_sCommissionGroupCode);
            System.out.println("getCommissionGroup.result=" + _getCommissionGroup__return);

        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransactionProduct...");
        java.util.List<java.lang.Integer> _getTransactionProduct_aTransactionIds = null;
        try {
            java.util.List<com.affiliatewindow.api.TransactionProduct> _getTransactionProduct__return = port.getTransactionProduct(_getTransactionProduct_aTransactionIds);
            System.out.println("getTransactionProduct.result=" + _getTransactionProduct__return);

        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransaction...");
        com.affiliatewindow.api.ATransactionId _getTransaction_aTransactionIds = null;
        try {
            com.affiliatewindow.api.GetTransactionReturn _getTransaction__return = port.getTransaction(_getTransaction_aTransactionIds);
            System.out.println("getTransaction.result=" + _getTransaction__return);

        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransactionList...");
        java.util.List<java.lang.Integer> _getTransactionList_aMerchantIds = null;
        javax.xml.datatype.XMLGregorianCalendar _getTransactionList_dStartDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getTransactionList_dEndDate = null;
        com.affiliatewindow.api.DateType _getTransactionList_sDateType = null;
        com.affiliatewindow.api.TransactionStatus _getTransactionList_sTransactionStatus = null;
        java.lang.Integer _getTransactionList_iOffset = null;
        java.lang.Integer _getTransactionList_iLimit = null;
        javax.xml.ws.Holder<com.affiliatewindow.api.GetTransactionListReturn> _getTransactionList_getTransactionListReturn = new javax.xml.ws.Holder<com.affiliatewindow.api.GetTransactionListReturn>();
        javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts> _getTransactionList_getTransactionListCountReturn = new javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts>();
        try {
            port.getTransactionList(_getTransactionList_aMerchantIds, _getTransactionList_dStartDate, _getTransactionList_dEndDate, _getTransactionList_sDateType, _getTransactionList_sTransactionStatus, _getTransactionList_iOffset, _getTransactionList_iLimit, _getTransactionList_getTransactionListReturn, _getTransactionList_getTransactionListCountReturn);

            System.out.println("getTransactionList._getTransactionList_getTransactionListReturn=" + _getTransactionList_getTransactionListReturn.value);
            System.out.println("getTransactionList._getTransactionList_getTransactionListCountReturn=" + _getTransactionList_getTransactionListCountReturn.value);
        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getClickStats...");
        javax.xml.datatype.XMLGregorianCalendar _getClickStats_dStartDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getClickStats_dEndDate = null;
        java.util.List<java.lang.Integer> _getClickStats_aMerchantIds = null;
        com.affiliatewindow.api.DateType _getClickStats_sDateType = null;
        java.lang.Integer _getClickStats_iOffset = null;
        java.lang.Integer _getClickStats_iLimit = null;
        javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.ClickStats>> _getClickStats_getClickStatsReturn = new javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.ClickStats>>();
        javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts> _getClickStats_getClickStatsCountReturn = new javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts>();
        try {
            port.getClickStats(_getClickStats_dStartDate, _getClickStats_dEndDate, _getClickStats_aMerchantIds, _getClickStats_sDateType, _getClickStats_iOffset, _getClickStats_iLimit, _getClickStats_getClickStatsReturn, _getClickStats_getClickStatsCountReturn);

            System.out.println("getClickStats._getClickStats_getClickStatsReturn=" + _getClickStats_getClickStatsReturn.value);
            System.out.println("getClickStats._getClickStats_getClickStatsCountReturn=" + _getClickStats_getClickStatsCountReturn.value);
        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getImpressionStats...");
        javax.xml.datatype.XMLGregorianCalendar _getImpressionStats_dStartDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getImpressionStats_dEndDate = null;
        java.util.List<java.lang.Integer> _getImpressionStats_aMerchantIds = null;
        com.affiliatewindow.api.DateType _getImpressionStats_sDateType = null;
        java.lang.Integer _getImpressionStats_iOffset = null;
        java.lang.Integer _getImpressionStats_iLimit = null;
        javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.ImpressionStats>> _getImpressionStats_getImpressionStatsReturn = new javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.ImpressionStats>>();
        javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts> _getImpressionStats_getImpressionStatsCountReturn = new javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts>();
        try {
            port.getImpressionStats(_getImpressionStats_dStartDate, _getImpressionStats_dEndDate, _getImpressionStats_aMerchantIds, _getImpressionStats_sDateType, _getImpressionStats_iOffset, _getImpressionStats_iLimit, _getImpressionStats_getImpressionStatsReturn, _getImpressionStats_getImpressionStatsCountReturn);

            System.out.println("getImpressionStats._getImpressionStats_getImpressionStatsReturn=" + _getImpressionStats_getImpressionStatsReturn.value);
            System.out.println("getImpressionStats._getImpressionStats_getImpressionStatsCountReturn=" + _getImpressionStats_getImpressionStatsCountReturn.value);
        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTransactionQuerys...");
        java.util.List<java.lang.Integer> _getTransactionQuerys_aMerchantIds = null;
        java.util.List<com.affiliatewindow.api.TransactionPreStatus> _getTransactionQuerys_aStatus = null;
        java.util.List<java.lang.String> _getTransactionQuerys_aClickRefs = null;
        java.lang.Integer _getTransactionQuerys_iOffset = null;
        java.lang.Integer _getTransactionQuerys_iLimit = null;
        javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.TransactionQuery>> _getTransactionQuerys_getTransactionQuerysReturn = new javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.TransactionQuery>>();
        javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts> _getTransactionQuerys_getTransactionQuerysCountReturn = new javax.xml.ws.Holder<com.affiliatewindow.api.RowCounts>();
        try {
            port.getTransactionQuerys(_getTransactionQuerys_aMerchantIds, _getTransactionQuerys_aStatus, _getTransactionQuerys_aClickRefs, _getTransactionQuerys_iOffset, _getTransactionQuerys_iLimit, _getTransactionQuerys_getTransactionQuerysReturn, _getTransactionQuerys_getTransactionQuerysCountReturn);

            System.out.println("getTransactionQuerys._getTransactionQuerys_getTransactionQuerysReturn=" + _getTransactionQuerys_getTransactionQuerysReturn.value);
            System.out.println("getTransactionQuerys._getTransactionQuerys_getTransactionQuerysCountReturn=" + _getTransactionQuerys_getTransactionQuerysCountReturn.value);
        } catch (ApiException_Exception e) { 
            System.out.println("Expected exception: ApiException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
