package com.affiliatewindow.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-06-18T17:32:55.013-07:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://api.affiliatewindow.com/", name = "ApiPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ApiPortType {

    @WebResult(name = "getCommissionGroupListReturn", targetNamespace = "http://api.affiliatewindow.com/")
    @RequestWrapper(localName = "getCommissionGroupList", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetCommissionGroupList")
    @WebMethod
    @ResponseWrapper(localName = "getCommissionGroupListResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetCommissionGroupListResponse")
    public java.util.List<com.affiliatewindow.api.CommissionGroup> getCommissionGroupList(
        @WebParam(name = "iMerchantId", targetNamespace = "http://api.affiliatewindow.com/")
        int iMerchantId
    ) throws ApiException_Exception;

    @WebResult(name = "getMerchantListReturn", targetNamespace = "http://api.affiliatewindow.com/")
    @RequestWrapper(localName = "getMerchantList", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetMerchantList")
    @WebMethod
    @ResponseWrapper(localName = "getMerchantListResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetMerchantListResponse")
    public java.util.List<com.affiliatewindow.api.Merchant> getMerchantList(
        @WebParam(name = "sRelationship", targetNamespace = "http://api.affiliatewindow.com/")
        com.affiliatewindow.api.Relationship sRelationship
    ) throws ApiException_Exception;

    @WebResult(name = "getMerchantReturn", targetNamespace = "http://api.affiliatewindow.com/")
    @RequestWrapper(localName = "getMerchant", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetMerchant")
    @WebMethod
    @ResponseWrapper(localName = "getMerchantResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetMerchantResponse")
    public java.util.List<com.affiliatewindow.api.Merchant> getMerchant(
        @WebParam(name = "aMerchantIds", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.Integer> aMerchantIds
    ) throws ApiException_Exception;

    @WebResult(name = "getCommissionGroupReturn", targetNamespace = "http://api.affiliatewindow.com/")
    @RequestWrapper(localName = "getCommissionGroup", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetCommissionGroup")
    @WebMethod
    @ResponseWrapper(localName = "getCommissionGroupResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetCommissionGroupResponse")
    public com.affiliatewindow.api.CommissionGroup getCommissionGroup(
        @WebParam(name = "iMerchantId", targetNamespace = "http://api.affiliatewindow.com/")
        int iMerchantId,
        @WebParam(name = "sCommissionGroupCode", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.String sCommissionGroupCode
    ) throws ApiException_Exception;

    @WebResult(name = "getTransactionProductReturn", targetNamespace = "http://api.affiliatewindow.com/")
    @RequestWrapper(localName = "getTransactionProduct", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionProduct")
    @WebMethod
    @ResponseWrapper(localName = "getTransactionProductResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionProductResponse")
    public java.util.List<com.affiliatewindow.api.TransactionProduct> getTransactionProduct(
        @WebParam(name = "aTransactionIds", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.Integer> aTransactionIds
    ) throws ApiException_Exception;

    @WebResult(name = "getTransactionReturn", targetNamespace = "http://api.affiliatewindow.com/")
    @RequestWrapper(localName = "getTransaction", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransaction")
    @WebMethod
    @ResponseWrapper(localName = "getTransactionResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionResponse")
    public com.affiliatewindow.api.GetTransactionReturn getTransaction(
        @WebParam(name = "aTransactionIds", targetNamespace = "http://api.affiliatewindow.com/")
        com.affiliatewindow.api.ATransactionId aTransactionIds
    ) throws ApiException_Exception;

    @RequestWrapper(localName = "getTransactionList", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionList")
    @WebMethod
    @ResponseWrapper(localName = "getTransactionListResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionListResponse")
    public void getTransactionList(
        @WebParam(name = "aMerchantIds", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.Integer> aMerchantIds,
        @WebParam(name = "dStartDate", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.datatype.XMLGregorianCalendar dStartDate,
        @WebParam(name = "dEndDate", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.datatype.XMLGregorianCalendar dEndDate,
        @WebParam(name = "sDateType", targetNamespace = "http://api.affiliatewindow.com/")
        com.affiliatewindow.api.DateType sDateType,
        @WebParam(name = "sTransactionStatus", targetNamespace = "http://api.affiliatewindow.com/")
        com.affiliatewindow.api.TransactionStatus sTransactionStatus,
        @WebParam(name = "iOffset", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iOffset,
        @WebParam(name = "iLimit", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iLimit,
        @WebParam(mode = WebParam.Mode.OUT, name = "getTransactionListReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<GetTransactionListReturn> getTransactionListReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "getTransactionListCountReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<RowCounts> getTransactionListCountReturn
    ) throws ApiException_Exception;

    @RequestWrapper(localName = "getClickStats", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetClickStats")
    @WebMethod
    @ResponseWrapper(localName = "getClickStatsResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetClickStatsResponse")
    public void getClickStats(
        @WebParam(name = "dStartDate", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.datatype.XMLGregorianCalendar dStartDate,
        @WebParam(name = "dEndDate", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.datatype.XMLGregorianCalendar dEndDate,
        @WebParam(name = "aMerchantIds", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.Integer> aMerchantIds,
        @WebParam(name = "sDateType", targetNamespace = "http://api.affiliatewindow.com/")
        com.affiliatewindow.api.DateType sDateType,
        @WebParam(name = "iOffset", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iOffset,
        @WebParam(name = "iLimit", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iLimit,
        @WebParam(mode = WebParam.Mode.OUT, name = "getClickStatsReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.ClickStats>> getClickStatsReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "getClickStatsCountReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<RowCounts> getClickStatsCountReturn
    ) throws ApiException_Exception;

    @RequestWrapper(localName = "getImpressionStats", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetImpressionStats")
    @WebMethod
    @ResponseWrapper(localName = "getImpressionStatsResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetImpressionStatsResponse")
    public void getImpressionStats(
        @WebParam(name = "dStartDate", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.datatype.XMLGregorianCalendar dStartDate,
        @WebParam(name = "dEndDate", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.datatype.XMLGregorianCalendar dEndDate,
        @WebParam(name = "aMerchantIds", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.Integer> aMerchantIds,
        @WebParam(name = "sDateType", targetNamespace = "http://api.affiliatewindow.com/")
        com.affiliatewindow.api.DateType sDateType,
        @WebParam(name = "iOffset", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iOffset,
        @WebParam(name = "iLimit", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iLimit,
        @WebParam(mode = WebParam.Mode.OUT, name = "getImpressionStatsReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.ImpressionStats>> getImpressionStatsReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "getImpressionStatsCountReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<RowCounts> getImpressionStatsCountReturn
    ) throws ApiException_Exception;

    @RequestWrapper(localName = "getTransactionQuerys", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionQuerys")
    @WebMethod
    @ResponseWrapper(localName = "getTransactionQuerysResponse", targetNamespace = "http://api.affiliatewindow.com/", className = "com.affiliatewindow.api.GetTransactionQuerysResponse")
    public void getTransactionQuerys(
        @WebParam(name = "aMerchantIds", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.Integer> aMerchantIds,
        @WebParam(name = "aStatus", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<com.affiliatewindow.api.TransactionPreStatus> aStatus,
        @WebParam(name = "aClickRefs", targetNamespace = "http://api.affiliatewindow.com/")
        java.util.List<java.lang.String> aClickRefs,
        @WebParam(name = "iOffset", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iOffset,
        @WebParam(name = "iLimit", targetNamespace = "http://api.affiliatewindow.com/")
        java.lang.Integer iLimit,
        @WebParam(mode = WebParam.Mode.OUT, name = "getTransactionQuerysReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<java.util.List<com.affiliatewindow.api.TransactionQuery>> getTransactionQuerysReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "getTransactionQuerysCountReturn", targetNamespace = "http://api.affiliatewindow.com/")
        javax.xml.ws.Holder<RowCounts> getTransactionQuerysCountReturn
    ) throws ApiException_Exception;
}
